title: iNQ – InnovationNQ

email: sean+inq@fierce.ventures

description: >
  Coworking space, offices, mentorship, events and more!

baseurl: ""

url: ""

markdown: kramdown

plugins:

exclude:
  - Gemfile
  - Gemfile.lock