title: iNQ – InnovationNQ

email: sean+inq@fierce.ventures

description: >
  Coworking space, offices, mentorship, events and more!

baseurl: ""

url: ""

includes_dir:    _includes

markdown: kramdown

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock